### ISSUE TITLE
command exited with code 4

### ISSUE THREAD

**Issue by jzhang52** [krlmlr/r-appveyor#106]
Anyone has any idea what might cause "command exited with code 4"? 
https://ci.appveyor.com/project/Brightspace/d2l-class-stream-t1gow/build/1.168.0

Thanks ahead!

**Comment by krlmlr** [comment]
I can't access this link:

![screenshot from 2018-02-24 14-51-53](https://user-images.githubusercontent.com/1741643/36631113-739553f6-1972-11e8-8d7c-6b4e4abe2125.png)

**Comment by jzhang52** [comment]
Hmm.. maybe because it's a private repo? 
I've copied over the console output. Hope that helps you to see the problem.. 

Thanks for looking into it! 

```
Build started
git clone -q --branch=master git@github.com:Brightspace/d2l-class-stream.git C:\projects\d2l-class-stream-t1gow
git checkout -qf d85f7c68bbb8cd9acd499a66c11b7580b40acc45
msbuild /t:restore  .\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium.sln
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2/23/2018 5:51:16 PM.
Project "C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium.sln" on node 1 (restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Restore:
  Restoring packages for C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj...
    GET https://api.nuget.org/v3-flatcontainer/nunit/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.console/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitprojectloader/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2driver/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2resultwriter/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.teamcityeventlistener/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.vsprojectloader/index.json
    GET https://api.nuget.org/v3-flatcontainer/nunit3testadapter/index.json
    GET https://api.nuget.org/v3-flatcontainer/selenium.rc/index.json
    GET https://api.nuget.org/v3-flatcontainer/selenium.support/index.json
    GET https://api.nuget.org/v3-flatcontainer/selenium.webdriver/index.json
    GET https://api.nuget.org/v3-flatcontainer/selenium.webdriverbackedselenium/index.json
    OK https://api.nuget.org/v3-flatcontainer/nunit/index.json 32ms
    GET https://api.nuget.org/v3-flatcontainer/nunit/3.0.0/nunit.3.0.0.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.teamcityeventlistener/index.json 70ms
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.teamcityeventlistener/1.0.2/nunit.extension.teamcityeventlistener.1.0.2.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2driver/index.json 76ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2resultwriter/index.json 75ms
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2driver/3.6.0/nunit.extension.nunitv2driver.3.6.0.nupkg
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2resultwriter/3.5.0/nunit.extension.nunitv2resultwriter.3.5.0.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.vsprojectloader/index.json 78ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.support/index.json 76ms
    OK https://api.nuget.org/v3-flatcontainer/nunit/3.0.0/nunit.3.0.0.nupkg 45ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.webdriver/index.json 96ms
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.vsprojectloader/3.5.0/nunit.extension.vsprojectloader.3.5.0.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.teamcityeventlistener/1.0.2/nunit.extension.teamcityeventlistener.1.0.2.nupkg 28ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2resultwriter/3.5.0/nunit.extension.nunitv2resultwriter.3.5.0.nupkg 22ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitv2driver/3.6.0/nunit.extension.nunitv2driver.3.6.0.nupkg 23ms
    OK https://api.nuget.org/v3-flatcontainer/nunit3testadapter/index.json 101ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitprojectloader/index.json 103ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.console/index.json 106ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/index.json 105ms
    GET https://api.nuget.org/v3-flatcontainer/selenium.support/2.48.2/selenium.support.2.48.2.nupkg
    GET https://api.nuget.org/v3-flatcontainer/selenium.webdriver/2.48.2/selenium.webdriver.2.48.2.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.vsprojectloader/3.5.0/nunit.extension.vsprojectloader.3.5.0.nupkg 91ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.webdriverbackedselenium/index.json 188ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.support/2.48.2/selenium.support.2.48.2.nupkg 88ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.rc/index.json 191ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.webdriver/2.48.2/selenium.webdriver.2.48.2.nupkg 86ms
    GET https://api.nuget.org/v3-flatcontainer/nunit3testadapter/3.0.7-ctp-7b/nunit3testadapter.3.0.7-ctp-7b.nupkg
    GET https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitprojectloader/3.5.0/nunit.extension.nunitprojectloader.3.5.0.nupkg
    GET https://api.nuget.org/v3-flatcontainer/nunit.console/3.7.0/nunit.console.3.7.0.nupkg
    GET https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.7.0/nunit.consolerunner.3.7.0.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit.extension.nunitprojectloader/3.5.0/nunit.extension.nunitprojectloader.3.5.0.nupkg 986ms
    OK https://api.nuget.org/v3-flatcontainer/nunit3testadapter/3.0.7-ctp-7b/nunit3testadapter.3.0.7-ctp-7b.nupkg 991ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.console/3.7.0/nunit.console.3.7.0.nupkg 987ms
    OK https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.7.0/nunit.consolerunner.3.7.0.nupkg 507ms
    GET https://api.nuget.org/v3-flatcontainer/selenium.rc/2.48.2/selenium.rc.2.48.2.nupkg
    GET https://api.nuget.org/v3-flatcontainer/selenium.webdriverbackedselenium/2.48.2/selenium.webdriverbackedselenium.2.48.2.nupkg
    OK https://api.nuget.org/v3-flatcontainer/selenium.rc/2.48.2/selenium.rc.2.48.2.nupkg 38ms
    OK https://api.nuget.org/v3-flatcontainer/selenium.webdriverbackedselenium/2.48.2/selenium.webdriverbackedselenium.2.48.2.nupkg 56ms
  Installing Selenium.WebDriver 2.48.2.
  Installing NUnit 3.0.0.
  Installing Selenium.WebDriverBackedSelenium 2.48.2.
  Installing NUnit.ConsoleRunner 3.7.0.
  Installing Selenium.RC 2.48.2.
  Installing NUnit3TestAdapter 3.0.7-ctp-7b.
  Installing Selenium.Support 2.48.2.
  Installing NUnit.Console 3.7.0.
  Installing NUnit.Extension.NUnitV2Driver 3.6.0.
  Installing NUnit.Extension.NUnitProjectLoader 3.5.0.
  Installing NUnit.Extension.VSProjectLoader 3.5.0.
  Installing NUnit.Extension.NUnitV2ResultWriter 3.5.0.
  Installing NUnit.Extension.TeamCityEventListener 1.0.2.
  Committing restore...
  Generating MSBuild file C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\obj\ParallelSelenium.csproj.nuget.g.props.
  Generating MSBuild file C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\obj\ParallelSelenium.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\obj\project.assets.json
  Restore completed in 6.49 sec for C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj.
  
  NuGet Config files used:
      C:\Users\appveyor\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.Fallback.config
  
  Feeds used:
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
      https://api.nuget.org/v3/index.json
  
  Installed:
      13 package(s) to C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj
Done Building Project "C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium.sln" (restore target(s)).
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:08.63
msbuild "C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
PageObjects\ActivityFeed\LoginPage.cs(37,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\LandingPage.cs(26,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\LandingPage.cs(38,26): warning CS0168: The variable 'ex' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\GradesPage.cs(20,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\AssignmentsPage.cs(24,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(148,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(189,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(211,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(328,14): warning CS0168: The variable 'activityTitle' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(663,14): warning CS0168: The variable 'editedTitle' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(798,11): warning CS0162: Unreachable code detected [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(818,51): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(830,51): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
PageObjects\ActivityFeed\CoursePage.cs(854,26): warning CS0168: The variable 'e' is declared but never used [C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ParallelSelenium.csproj]
  ParallelSelenium -> C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\bin\Debug\ParallelSelenium.dll
Discovering tests...OK
nunit3-console "C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\bin\Debug\ParallelSelenium.dll"
NUnit Console Runner 3.7.0 
Copyright (c) 2017 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000
Test Files
    C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\bin\Debug\ParallelSelenium.dll
Tests Not Run
1) Ignored : ParallelSelenium.ActivityFeedUiTests("Chrome","latest","Windows 10","","").ValidateShadowDomElementLocator
CustomFindElement test is unreliable
2) Ignored : ParallelSelenium.ActivityFeedUiTests("Firefox","latest","Windows 10","","").ValidateShadowDomElementLocator
CustomFindElement test is unreliable
Errors, Failures and Warnings
1) Error : ParallelSelenium.ActivityFeedUiTests("Chrome","latest","Windows 10","","").MessagePosts
System.NullReferenceException : Object reference not set to an instance of an object.
   at ParallelSelenium.PageObjects.ActivityFeed.CoursePage.CreateMessagePost(String message) in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\PageObjects\ActivityFeed\CoursePage.cs:line 165
   at ParallelSelenium.ActivityFeedUiTests.MessagePosts() in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ActivityFeedUiTests.cs:line 133
2) Error : ParallelSelenium.ActivityFeedUiTests("Chrome","latest","Windows 10","","").PlannedMessagePosts
System.NullReferenceException : Object reference not set to an instance of an object.
   at ParallelSelenium.PageObjects.ActivityFeed.CoursePage.CreatePlannedMessagePost(String message, String postdate, String posttime) in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\PageObjects\ActivityFeed\CoursePage.cs:line 181
   at ParallelSelenium.ActivityFeedUiTests.PlannedMessagePosts() in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ActivityFeedUiTests.cs:line 243
3) Error : ParallelSelenium.ActivityFeedUiTests("Firefox","latest","Windows 10","","").MessagePosts
System.NullReferenceException : Object reference not set to an instance of an object.
   at ParallelSelenium.PageObjects.ActivityFeed.CoursePage.CreateMessagePost(String message) in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\PageObjects\ActivityFeed\CoursePage.cs:line 165
   at ParallelSelenium.ActivityFeedUiTests.MessagePosts() in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ActivityFeedUiTests.cs:line 133
4) Error : ParallelSelenium.ActivityFeedUiTests("Firefox","latest","Windows 10","","").PlannedMessagePosts
System.NullReferenceException : Object reference not set to an instance of an object.
   at ParallelSelenium.PageObjects.ActivityFeed.CoursePage.CreatePlannedMessagePost(String message, String postdate, String posttime) in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\PageObjects\ActivityFeed\CoursePage.cs:line 181
   at ParallelSelenium.ActivityFeedUiTests.PlannedMessagePosts() in C:\projects\d2l-class-stream-t1gow\UIAutomation\ActivityfeedUITestAutomation\ParallelSelenium\ActivityFeedUiTests.cs:line 243
Run Settings
    DisposeRunners: True
    WorkDirectory: C:\projects\d2l-class-stream-t1gow
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 2
Test Run Summary
  Overall result: Failed
  Test Count: 12, Passed: 6, Failed: 4, Warnings: 0, Inconclusive: 0, Skipped: 2
    Failed Tests - Failures: 0, Errors: 4, Invalid: 0
    Skipped Tests - Ignored: 2, Explicit: 0, Other: 0
  Start time: 2018-02-24 01:51:34Z
    End time: 2018-02-24 02:00:24Z
    Duration: 530.251 seconds
Results (nunit3) saved as TestResult.xml
Command exited with code 4
```

**Comment by krlmlr** [comment]
Is your project using r-appveyor at all? Please contact AppVeyor support for general issues.

**Comment by jzhang52** [comment]
Ah, I'm sorry, didn't realize this place is for R+AppVeyor. My question is about just AppVeyor. Thanks.
